config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"
  resources :posts do
    resources :replies

    member do
      post :favorite
      post :unfavorite
    end

    collection do
      get :feeds
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :posts
      get :comments
      get :collects
      get :drafts
      get :friends
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      post :confirm
      delete :refuse
    end
  end

  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "categories#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
  # 加上驗證 name 不能重覆 (關鍵字提示: uniqueness)
  validates_uniqueness_of :name
  mount_uploader :avatar, AvatarUploader

  has_many :posts, dependent: :destroy

  has_many :replies, dependent: :destroy

  has_many :favorites,dependent: :destroy

  has_many :friendships, -> {where status: true}, dependent: :destroy #我想加好友的 (已成為好友）)
  has_many :friends,through: :friendships,source: :friend

  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :friend_asks, through: :inverse_friendships, source: :user #想加我好友的 （已成為好友）

  has_many :unconfirm_friendships, -> {where status: false}, class_name: "Friendship", dependent: :destroy
  has_many :unconfirm_friends, through: :unconfirm_friendships, source: :friend #等待邀請回覆(未成為好友)

  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :request_friends, through: :request_friendships, source: :user #想加我好友的 #是否接受邀請 (未成為好友)

  def admin?
    self.role == "admin"
  end

  def friend?(user) #user的好友
    self.friends.include?(user)|| self.friend_asks.include?(user) #||(邏輯運算子):或者
  end

  def unconfirm_friend?(user) #user加別人好友(等待邀請回覆)
    self.unconfirm_friends.include?(user)
  end

  def request_friend?(user)
    self.request_friends.include?(user)
  end

  def all_friends
    friends = self.friends + self.friend_asks
    return friends.uniq #不要重複
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin
  def index 
    @users = User.order(created_at: :asc)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
      flash[:notice] = "user was successfully updated"
    end
  end

  private

  def user_params
    params.require(:user).permit(:role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "user info was successfully updated"
      redirect_to posts_user_path(@user)
    else
      flash[:alert] = "user info was failed to update"
      render :edit 
    end
  end 


  def posts
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: true).order(created_at: :desc)
  end 

  def comments
    @user = User.find(params[:id])
    @comments = @user.replies.order(created_at: :desc)
  end

  def collects
    @user = User.find(params[:id])
    @collects = @user.favorites.order(created_at: :desc)
  end

  def drafts
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: false).order(created_at: :desc)
  end

  def friends
    @user = User.find(params[:id])
    @friends = @user.all_friends
    @unconfirm_friends = @user.unconfirm_friends
    @request_friends = @user.request_friends
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar, :introduction)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/collects.html.erb
<div class="container">  
  <div class="row">
    <div class="col-md-12">
      <%= render partial:"shared/user_info",locals:{:user => @user} %>

      <div class="clearfix"></div>

      <br><br><br>
            
      <ul class="nav nav-tabs">
        <% if @user == current_user %>
          <li role="presentation"><%= link_to "My Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "My Comment", comments_user_path %></li>
          <li role="presentation" class="active"><%= link_to "My Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "My Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "My Friend", friends_user_path %></li>
        <% else %>
          <li role="presentation"><%= link_to "#{@user.name}'s Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Comment", comments_user_path %></li>
          <li role="presentation" class="active"><%= link_to "#{@user.name}'s Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Friend", friends_user_path %></li>
        <% end %>        
      </ul>
      

      <br><br>

      <div class="col-md-12">
        <div class="">
          <table class="table">
            <tbody>
              <% @collects.each do |collect| %>
                <tr>
                  <td><%= link_to collect.post.title, post_path(collect.post) %></td>
                  <td><%= render partial:"shared/favorite",locals:{post: collect.post} %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div> 
    </div>
  </div>
</div>

app/views/users/comments.html.erb
<div class="container">  
  <div class="row">
    <div class="col-md-12">
      <%= render partial:"shared/user_info",locals:{:user => @user} %>

      <div class="clearfix"></div>

      <br><br><br>
      
      <ul class="nav nav-tabs">
        <% if @user == current_user %>
          <li role="presentation"><%= link_to "My Post", posts_user_path %></li>
          <li role="presentation" class="active"><%= link_to "My Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "My Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "My Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "My Friend", friends_user_path %></li>
        <% else %>
          <li role="presentation"><%= link_to "#{@user.name}'s Post", posts_user_path %></li>
          <li role="presentation" class="active"><%= link_to "#{@user.name}'s Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Friend", friends_user_path %></li>
        <% end %>        
      </ul>
      
      <br><br>
      
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="text-center" style="font-size: 25px;">Post Title</th>
            <th class="text-center" style="font-size: 25px;">Comment</th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |reply| %>
            <tr id="reply_<%= reply.id %>" class="reply-background">
              <td class="col-md-5">
                <div class="text-center post-content">
                  <%= link_to reply.post.title, post_path(reply.post) %>
                </div>
              </td>

              <td class="col-md-7">
                <div class="reply-content">
                  <span><%= reply.content %></span>
                  <br>

                  <% if current_user == reply.user || current_user.admin? %>
                    <%= link_to post_reply_path(reply.post,reply), remote: true ,method: :delete, data: { confirm: "確定要刪除這個留言嗎?"} do %>
                      <span class="glyphicon glyphicon-remove post-icon"></span>
                    <% end %>
                  <% end %>

                  <% if current_user == reply.user %>
                    <%= link_to edit_post_reply_path(reply.post,reply),remote: true do %>
                      <span class="glyphicon glyphicon-pencil post-icon"></span>
                    <% end %>
                  <% end %>
                </div>
              </td>
            </tr> 
          <% end %>
        </tbody>
      </table>
      
    </div>
  </div>
</div>

app/views/users/drafts.html.erb
<div class="container">  
  <div class="row">
    <div class="col-md-12">
      <%= render partial:"shared/user_info",locals:{:user => @user} %>

      <div class="clearfix"></div>

      <br><br><br>
      
      <ul class="nav nav-tabs">
        <% if @user == current_user %>
          <li role="presentation"><%= link_to "My Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "My Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "My Collect", collects_user_path %></li>
          <li role="presentation" class="active"><%= link_to "My Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "My Friend", friends_user_path %></li>
        <% else %>
          <li role="presentation"><%= link_to "#{@user.name}'s Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Collect", collects_user_path %></li>
          <li role="presentation" class="active"><%= link_to "#{@user.name}'s Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Friend", friends_user_path %></li>
        <% end %>        
      </ul>
      

      <br><br>

      <div class="col-md-12">
        <% if @user == current_user %>
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Status</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td><%= link_to post.title, post_path(post) %></td>
                  <td>Draft</td>
                  <td><%= post.created_at.strftime("%Y-%m-%d") %></td>
                  <td>
                    <%= link_to post_path(post), method: :delete, data: { confirm: "確定要刪除本則貼文嗎?"} do %>
                      <span class="glyphicon glyphicon-remove post-icon"></span>
                    <% end %>
                  

                    <%= link_to edit_post_path(post) do %>
                      <span class="glyphicon glyphicon-pencil post-icon"></span>
                    <% end %>
                  </td>
                </tr>                
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class="text-center" style="font-size: 25px;">對不起，只有作者本人有合法權限去觀看此項紀錄</div>
        <% end %>
        
      </div> 
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<style>
  .error-box{
    border: 1px solid #ddd;
    padding: 10px;
    margin-bottom: 15px;
  }
</style>

<div class="container">
  <div class="col-md-8 col-md-offset-2" style="margin-top: 40px;">   
    <% if @user.errors.any? %>
      <div class="error-box">
        <h4>We have some errors here !</h4>
        <ol>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ol>
      </div>        
    <% end %>

    <%= form_for @user,method: :put do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name", class: "edit-title" %>
        <%= f.text_field :name, class: "form-control" %>
      </div><br>

      <div class="form-group">
        <%= f.label :introduction, "Introduction" %>
        <%= f.text_area :introduction,rows:"5", class: "form-control" %>
      </div><br>

      <div class="form-group">
        <%= f.label :avatar, "Avatar" %><br>
        <%= image_tag @user.avatar.url, width: '150px' if @user.avatar? %><br>
        <%= f.file_field :avatar %>
      </div>

      <div class="form-group">
        <%= f.submit "Update", class: "btn btn-primary" %>
        <%= link_to 'Cancel', posts_user_path(@user), class: "btn btn-danger" %>
      </div>
    <% end %>
  
  </div>
</div>

app/views/users/friends.html.erb
<div class="container">  
  <div class="row">
    <div class="col-md-12">
      <%= render partial:"shared/user_info",locals:{:user => @user} %>

      <div class="clearfix"></div>

      <br><br><br>
            
      <ul class="nav nav-tabs">
        <% if @user == current_user %>
          <li role="presentation"><%= link_to "My Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "My Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "My Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "My Draft", drafts_user_path %></li>
          <li role="presentation" class="active"><%= link_to "My Friend", friends_user_path %></li>
        <% else %>
          <li role="presentation"><%= link_to "#{@user.name}'s Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Draft", drafts_user_path %></li>
          <li role="presentation" class="active"><%= link_to "#{@user.name}'s Friend", friends_user_path %></li>
        <% end %>        
      </ul>
      

      <br><br>


      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= @user.all_friends.count %>
            個好友
          </div>
          <div class="panel-center panel-body">
            <div id="my-friends">
              <% @friends.each do |friend| %>
                <div class="friend-item text-center col-xs-12 col-sm-6 col-md-3">
                  <%= image_tag friend.avatar.url,width:"100" if friend.avatar? %>
                  <p class="text-primary inline">
                    <%= link_to friend.name, posts_user_path(friend) %>
                  </p>
                  <%= render partial: "shared/friend", locals: { user: friend } %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <% if @user == current_user %>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= @user.unconfirm_friends.count %>
              個等待接受好友
            </div>
            <div class="panel-center panel-body">
              <% @unconfirm_friends.each do |friend| %>
                <div class="friend-item text-center col-xs-12 col-sm-6 col-md-3">
                  <%= image_tag friend.avatar.url,width:"100" if friend.avatar? %>
                  <p class="text-primary inline">
                    <%= link_to friend.name, posts_user_path(friend) %>
                  </p>
                  <%= render partial: "shared/friend", locals: { user: friend } %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= @user.request_friends.count %>
              個好友請求
            </div>
            <div class="panel-center panel-body">
              <% @request_friends.each do |friend| %>
                <div class="friend-item text-center col-xs-12 col-sm-6 col-md-3">
                  <%= image_tag friend.avatar.url,width:"100" if friend.avatar? %>
                  <p class="text-primary inline">
                    <%= link_to friend.name, posts_user_path(friend) %>
                  </p>
                  <p><%= link_to "接受好友邀請", confirm_friendship_path(current_user, friend), class: "btn btn-primary",method: :post %></p>
                  <p><%= link_to "拒絕好友邀請", refuse_friendship_path(current_user, friend), class: "btn btn-danger", method: :delete %></p>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/posts.html.erb
<div class="container">  
  <div class="row">
    <div class="col-md-12">
      <%= render partial:"shared/user_info",locals:{:user => @user} %>

      <div class="clearfix"></div>

      <br><br><br>

      <ul class="nav nav-tabs">
        <% if @user == current_user %>
          <li role="presentation" class="active"><%= link_to "My Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "My Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "My Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "My Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "My Friend", friends_user_path %></li>
        <% else %>
          <li role="presentation" class="active"><%= link_to "#{@user.name}'s Post", posts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Comment", comments_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Collect", collects_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Draft", drafts_user_path %></li>
          <li role="presentation"><%= link_to "#{@user.name}'s Friend", friends_user_path %></li>
        <% end %>        
      </ul>
      
      <br>

      <div class="col-md-12">
        <div class="">
          <table class="table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Status</th>
                <th>Date</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @posts.each do |post| %>
                <% if current_user %>  
                  <% if post.authority == "All" || post.authority == "Friend" %>
                    <tr>
                      <td><%= link_to post.title, post_path(post) %></td>
                      <td>Published</td>
                      <td><%= post.created_at.strftime("%Y-%m-%d") %></td>
                      <td>
                        <% if current_user == post.user || current_user.admin? %>
                          <%= link_to post_path(post), method: :delete, data: { confirm: "確定要刪除本則貼文嗎?"} do %>
                            <span class="glyphicon glyphicon-remove post-icon"></span>
                          <% end %>
                        <% end %>

                        <% if current_user == post.user %>
                          <%= link_to edit_post_path(post) do %>
                            <span class="glyphicon glyphicon-pencil post-icon"></span>
                          <% end %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %> 
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div> 
    </div>
  </div>
</div>