config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"
  resources :posts do
    resources :replies

    member do
      post :favorite
      post :unfavorite
    end

    collection do
      get :feeds
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :posts
      get :comments
      get :collects
      get :drafts
      get :friends
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      post :confirm
      delete :refuse
    end
  end

  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "categories#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/views/shared/_favorite.html.erb
<div id="favorite-<%= post.id%>">
  <% if post.is_favorited?(current_user) %>
    <%= link_to 'Uncollect',unfavorite_post_path(post),remote: true,method: :post,class: "btn btn-warning"%>
  <% else %>
    <%= link_to 'Collect', favorite_post_path(post),remote: true, method: :post, class: "btn btn-default" %>
  <% end %>
</div>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user) %>
    <%= link_to '取消好友',friendship_path(user),method: :delete,class:"btn btn-danger" %>
  <% elsif current_user.unconfirm_friend?(user) %>
    <%= link_to '收回好友邀請',friendship_path(user),method: :delete,class:"btn btn-warning" %>
  <% elsif current_user.request_friend?(user) %>
    <label class="label label-info">等待回覆</label>
  <% else %>
    <%= link_to '要求成為好友',friendships_path(friend_id:user),method: :post,class:"btn btn-success" %>            
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top ">
  <div class="container-fluid">        
    <div class="navbar-header">
        <%= link_to "DojoForum",root_path,class:"navbar-brand" %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span> 
        </button>
    </div>
    
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-left">
          <li style="font-size: 15px;"><%= link_to "Feeds",feeds_posts_path %></li>
          <li style="font-size: 15px;"><%= link_to "All Posts",posts_path %></li>
          <li style="font-size: 15px;"><%= link_to "New Post",new_post_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right"> 
        <% if current_user %>         
          
          <li style="font-size: 15px;">
            <p class="navbar-text"><%= current_user.email %></p>
          </li>

          <li style="font-size: 15px;"><%= link_to "(Admin)",admin_categories_path %>
          </li> 

          <li style="font-size: 15px;"><%= link_to posts_user_path(current_user) do %>
            <span class="glyphicon glyphicon-pencil"></span> Profile
          <% end %>
          </li> 

          <li style="font-size: 15px;"><%= link_to destroy_user_session_path, method: :delete do%>
           <span class="glyphicon glyphicon-log-out"></span> Log out
          <% end %> 
          </li> 


         <% else %>
          <li><%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-registration-mark"></span> 註冊
            <% end %>
          </li>

          <li><%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span> 登入
           <% end %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/shared/_post_show.html.erb
<div class="post-title">
  <h2 class="pull-left"><%= @post.title %><h2>
  <h2 class="pull-right"><%= render partial:"shared/favorite",locals:{post: @post} %></h2>  
  <div class="clearfix"></div>
  <% @post.categories.each do |category| %>
    <span style="font-size: 10px;margin-left: 5px;padding: 8px;letter-spacing: 2px;" class="label label-success"><%= category.name %></span>  
  <% end %> 
</div>

<br>

<div class="post-item">
  <table class="table table-bordered">
    <tbody>
      <!--post content-->
      <tr>
        <td class="col-md-3">
          <div class="text-center post-content">
            <%= link_to posts_user_path(@post.user) do %>
              <%= image_tag @post.user.avatar.url,width:"150" if @post.user.avatar? %>
              <div style="margin-top: 20px;"><%= @post.user.name %></div><br>
              <%= render partial: "shared/friend", locals: { user: @post.user } %>
            <% end %>
          </div>
        </td>

        <td class="col-md-9">
          <div class="post-content">
            <%= image_tag @post.image.url,width:"500px",height:"300px" if @post.image? %>

            <p style="margin-top: 15px;"><%= @post.content %></p>

            <% if current_user == @post.user || current_user.admin? %>
              <%= link_to post_path(@post), method: :delete, data: { confirm: "確定要刪除本則貼文嗎?"} do %>
                <span class="glyphicon glyphicon-remove post-icon"></span>
              <% end %>
            <% end %>

            <% if current_user == @post.user %>
              <%= link_to edit_post_path(@post) do %>
                <span class="glyphicon glyphicon-pencil post-icon"></span>
              <% end %>
            <% end %>
          </div>
        </td>
      </tr>       

      <!--reply content-->  
      <% @replies.each do |reply| %>
        <%= render :partial => 'replies/reply', locals: {reply: reply } %>
      <% end %>
       
    </tbody>
  </table>
</div>

<div class="post-reply">
  <%= form_for [@post, @reply] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, rows:"3", placeholder: "請寫下留言內容", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit" ,class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<div class="col-md-10 col-md-offset-1 user-info">
  <div class="col-md-3 text-center">
    <%= image_tag user.avatar.url,width:"150" if user.avatar? %>
    <div style="margin-top: 10px;font-size: 20px;"><%= user.name %></div>
  </div>

  <div class="col-md-8" style="margin-top: 20px;">
    <p><%= simple_format user.introduction,style:"font-size:16px;" %></p>
    <% if user == current_user %>
      <%= link_to 'Edit', edit_user_path(user), class: "btn btn-default pull-right"%>
    <% else %>
      <span class="pull-right">
        <%= render partial: "shared/friend", locals: { user: user } %>
      </span>
    <% end %>
  </div>
</div>