config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"
  resources :posts do
    resources :replies

    member do
      post :favorite
      post :unfavorite
    end

    collection do
      get :feeds
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :posts
      get :comments
      get :collects
      get :drafts
      get :friends
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      post :confirm
      delete :refuse
    end
  end

  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "categories#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  
  #has_many :posts, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories, source: :post
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin
  def index
    @categories = Category.order(created_at: :desc)
    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end
  end 

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      flash[:alert] ="category name cannot be blank"
      redirect_to admin_categories_path
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "category was successfully updated"
    else
      flash[:alert] ="category name cannot be blank"
      redirect_to admin_categories_path
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "category was successfully deleted"
    redirect_to admin_categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    #@posts = @category.posts.where(status:true).order(created_at: :desc).page(params[:page]).per(10)
    @q = @category.posts.where(status: true).ransack(params[:q])
    @posts = @q.result.order(id: :asc).page(params[:page]).per(20)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center" style="letter-spacing: 2px;">管理員後台</h2><br>
    <div class="col-md-10 col-md-offset-1">
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><%= link_to "Category List", admin_categories_path %></li>
        <li role="presentation"><%= link_to "User List", admin_users_path %></li>        
      </ul>

      <br>

      <div class="form-inline" >
        <%= form_for [:admin, @category] do |f| %>
          <div class="form-group">
            <%= f.text_field :name, placeholder: "category name", class: "form-control" %>
          </div>
          <%= f.submit class: "btn btn-primary" %>
          <%= link_to "Cancel", admin_categories_path,class:"btn btn-danger" if @category.id.present? %>  
        <% end %>
      </div>  

      <br>

      <table class="table table-bordered">
        <thead>
          <tr class="active">
            <th class="text-center">Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td class="text-center"><%= category.name %></td>
              <td class="text-center">
                <%= link_to 'Edit', admin_categories_path(id: category.id), class: "btn btn-success" %>
                <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>