config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"
  resources :posts do
    resources :replies

    member do
      post :favorite
      post :unfavorite
    end

    collection do
      get :feeds
    end
  end

  resources :users, only: [:edit, :update] do
    member do
      get :posts
      get :comments
      get :collects
      get :drafts
      get :friends
    end
  end

  resources :friendships, only: [:create, :destroy] do
    member do
      post :confirm
      delete :refuse
    end
  end

  resources :categories, only: [:show]

  namespace :admin do
    resources :categories
    resources :users, only: [:index, :update]
    root "categories#index"
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  
  #has_many :posts, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :posts, through: :post_categories, source: :post
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :authenticate_admin
  def index
    @categories = Category.order(created_at: :desc)
    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end
  end 

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path
    else
      flash[:alert] ="category name cannot be blank"
      redirect_to admin_categories_path
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "category was successfully updated"
    else
      flash[:alert] ="category name cannot be blank"
      redirect_to admin_categories_path
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "category was successfully deleted"
    redirect_to admin_categories_path
  end

  def category_params
    params.require(:category).permit(:name)
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    #@posts = @category.posts.where(status:true).order(created_at: :desc).page(params[:page]).per(10)
    @q = @category.posts.where(status: true).ransack(params[:q])
    @posts = @q.result.order(id: :asc).page(params[:page]).per(20)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">DojoForum</h1>

    <div class="col-md-12">
      <ul class="nav nav-pills nav-pills-center" style="margin-top:25px;">
        <li role="presentation"><%= link_to "All", root_path %></li>
        <% @categories.each do |category| %>
          <li role="presentation" class="<%= "active" if category == @category %>">
            <%= link_to category.name, category_path(category) %>
          </li>
        <% end %>
      </ul>

      <table class="table" style="margin-top:16px;">
        <thead>
          <tr>
            <th><%= sort_link(@q, :replies_count, 'Replies Count', default_order: :desc) %></th>
            <th>Title</th>
            <th><%= sort_link(@q, :last_replied_at, 'Last replied at', default_order: :desc) %></th>
            <th><%= sort_link(@q, :viewed_count, 'Viewed Count', default_order: :desc) %></th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <% if current_user %>
              <% if current_user.admin? || current_user == post.user || post.authority == "All" || post.authority == "Friend" %>
                <tr>
                  <td class="text-center"><%= post.replies_count %></td>
                  <td><%= link_to post.title, post_path(post) %></td>
                  <td><%= post.last_replied_at.try(:strftime,("%Y-%m-%d")) %></td>
                  <td class="text-center"><%= post.viewed_count %></td>
                </tr>
              <% end %>
            
            <% else %>
              <% if post.authority == "All" %>
                <tr>
                  <td class="text-center"><%= post.replies_count %></td>
                  <td><%= link_to post.title, post_path(post) %></td>
                  <td><%= post.last_replied_at.try(:strftime,("%Y-%m-%d")) %></td>
                  <td class="text-center"><%= post.viewed_count %></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= paginate @posts %>
      </div> 

    </div>

  </div>
</div>
 